/* ══════════════════════════════════════════
   GIRLY GYM DOLPH — Gym_Program-GitHub.js
   Layer 3 · Emily's training program
   Last updated: July 2026
   schemaVersion: 0.9.9
   Never sourced from Gym Dolph ZIP.
   Clinicians: "PT" / "Physio/Osteo" — never named.
══════════════════════════════════════════ */

window.PROGRAM = {
  schemaVersion: '0.9.9',
  meta: {
    title: "Emily's Program",
    framework: 'POTS-safe strength, stability & pregnancy prep',
    gym: 'Banyule Leisure — Ivanhoe Aquatic & Fitness Centre, Ivanhoe VIC',
  },
  phases: [],

  milestones: {
    startDate: '2026-07-04',

    performance: [
      {
        target: 'Complete a full D1–D4 training week without skipping a session',
        timeline: 'Now',
        metric: 'Consistency',
        icon: '🫧',
      },
      {
        target: 'Complete 4 consecutive training weeks with manageable POTS symptom load',
        timeline: 'Month 1',
        metric: 'Consistency',
        icon: '🐟',
      },
      {
        target: 'Progress leg press weight by 10 kg from opening session',
        timeline: 'Month 2',
        metric: 'Lower body strength',
        icon: '🐠',
      },
      {
        target: 'Complete D5 Block A steady state at Zone 2 for 20 min without dizziness',
        timeline: 'Month 3',
        metric: 'Cardio capacity',
        icon: '🐬',
      },
      {
        target: 'Progress hip thrust machine weight by 15 kg from opening session',
        timeline: 'Month 4',
        metric: 'Glute strength',
        icon: '🦈',
      },
    ],

    bodycomp: [
      {
        target: 'Feel stronger and more energised during nursing and midwifery shifts',
        timeline: 'Month 2',
        metric: 'Wellbeing',
        icon: '🌸',
      },
      {
        target: 'Notice improved posture and less end-of-shift fatigue',
        timeline: 'Month 3',
        metric: 'Posture & energy',
        icon: '⚡',
      },
      {
        target: 'Feel fit and strong — physically ready for pregnancy',
        timeline: '4-6 months',
        metric: 'Pregnancy prep',
        icon: '🌿',
      },
    ],
  },

  days: [

    /* ── D1 · Lower Body ── */
    {
      id: 'D1',
      name: 'Lower Body',
      type: 'training',
      duration: 50,
      note: 'POTS — rise slowly from any cardio machine before standing work. hEDS — stop short of joint lockout on all machines.',
      blocks: [
        {
          id: 'D1-warmup',
          type: 'warmup',
          bodyPart: 'Warm-Up',
          icon: '🔥',
          duration: '8 min',
          exercises: [
            {
              id: 'D1-w1a', name: 'Recumbent Bike',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'PRIMARY - Easy pace, low resistance. POTS: back fully supported. Rise slowly after.',
              muscles: 'Cardiovascular warm-up · Quads · Calves',
              cues: ['Keep resistance very low — this is circulation, not cardio', 'Seat back fully reclined', 'POTS: stay seated for 10–15 sec after stopping before standing'],
              yt: 'recumbent bike warm up technique',
            },
            {
              id: 'D1-w1b', name: 'Rower',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 1 - Easy pace, damper 3–4. Seated — good POTS option. hEDS: avoid aggressive pull.',
              muscles: 'Cardiovascular warm-up · Back · Legs',
              cues: ['Damper 3–4, easy pace', 'hEDS: controlled drive — no explosive pull', 'POTS: good seated alternative to recumbent bike'],
              yt: 'rowing machine beginner technique',
            },
            {
              id: 'D1-w1c', name: 'Treadmill (Incline Walk)',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 2 - 4–6% incline, slow pace. POTS: hold rails if needed. Rise slowly after.',
              muscles: 'Cardiovascular warm-up · Glutes · Calves',
              cues: ['4–6% incline, slow walking pace', 'POTS: hold rails if unsteady', 'POTS: pause on treadmill for 10 sec before stepping off'],
              yt: 'treadmill incline walk warm up',
            },
            {
              id: 'D1-w1d', name: 'Stairmaster',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 3 - Low speed. POTS: hold rails throughout. Skip on high-symptom days.',
              muscles: 'Cardiovascular warm-up · Glutes · Quads · Calves',
              cues: ['Lowest comfortable speed', 'POTS: hold rails throughout — do not let go', 'Skip entirely on high-symptom days'],
              yt: 'stairmaster beginner technique',
            },
            {
              id: 'D1-w2', name: 'Seated Ankle Rolls + Calf Pumps',
              prescription: '1 x 15', sets: 1, reps: 15,
              note: 'POTS: venous return activation before standing.',
              muscles: 'Ankle stabilisers · Calf pump',
              cues: ['Slow full circles each direction', 'Then flex and point 15 times', 'POTS: activates calf pump to push blood back up before standing'],
              yt: 'ankle circles calf pumps seated',
              bodyweight: true,
            },
            {
              id: 'D1-w3', name: 'Seated Leg Swings + Hip Circles',
              prescription: '1 x 10', sets: 1, reps: 10,
              note: 'Bodyweight. Hold rail — rise slowly from cardio machine first.',
              muscles: 'Hip flexors · Glutes · Hip stabilisers',
              cues: ['Hold wall or rail for balance', 'Controlled swing — not momentum-driven', 'hEDS: comfortable range only, no end-range flick'],
              yt: 'seated leg swings hip circles warm up',
              bodyweight: true,
            },
          ],
        },
        {
          id: 'D1-main',
          type: 'main',
          bodyPart: 'Legs',
          icon: '🦵',
          duration: '25 min',
          exercises: [
            {
              id: 'D1-m1', name: 'Seated Leg Press',
              prescription: '3 x 10–12', sets: 3, reps: 12,
              note: 'Controlled tempo. hEDS: stop short of full knee lockout. Back flat against pad.',
              muscles: 'Quads · Glutes · Hamstrings',
              cues: ['Feet hip-width, mid-platform', 'hEDS: stop just before knees fully straighten — never lock out', 'Control the return — 2–3 sec lowering', 'Back stays flat against pad throughout'],
              yt: 'leg press machine form technique',
            },
            {
              id: 'D1-m2', name: 'Leg Extension Machine',
              prescription: '3 x 12–15', sets: 3, reps: 15,
              note: '3 sec lowering phase. hEDS: avoid snapping to full lockout — stop just short.',
              muscles: 'Quadriceps (isolation)',
              cues: ['hEDS: stop 5–10° before full knee extension', 'Lower slowly — 3 seconds down', 'Squeeze quad at top but do not snap into lockout', 'Seated upright throughout'],
              yt: 'leg extension machine form',
            },
            {
              id: 'D1-m3', name: 'Seated Leg Curl',
              prescription: '3 x 12–15', sets: 3, reps: 15,
              note: 'hEDS: work in comfortable mid-range, do not force full range.',
              muscles: 'Hamstrings · Gastrocnemius',
              cues: ['hEDS: work mid-range — stop before full stretch or full contraction', 'Smooth controlled movement both ways', 'No jerking or momentum'],
              yt: 'seated leg curl machine technique',
            },
          ],
        },
        {
          id: 'D1-prehab',
          type: 'prehab',
          bodyPart: 'Glutes & Calves',
          icon: '🍑',
          duration: '17 min',
          exercises: [
            {
              id: 'D1-s1', name: 'Hip Thrust Machine',
              prescription: '3 x 12–15', sets: 3, reps: 15,
              note: 'Squeeze at top. hEDS: stop at neutral hip — never hyperextend. Key for POTS venous return.',
              muscles: 'Glutes · Hamstrings',
              cues: ['Drive through heels', 'Squeeze glutes hard at top — hold 1 sec', 'hEDS: stop when hips are level with torso — do not push further back', 'POTS: this exercise directly supports venous return'],
              yt: 'hip thrust machine glutes form',
            },
            {
              id: 'D1-s2', name: 'Inner / Outer Thigh Machine',
              prescription: '3 x 15', sets: 3, reps: 15,
              note: 'Each direction. Slow and controlled. Hip stability + pregnancy prep.',
              muscles: 'Adductors (inner) · Abductors / Gluteus medius (outer)',
              cues: ['Do both directions in one sitting — just switch the pin', 'Slow controlled movement — no crashing the weight', 'hEDS: work in comfortable range', 'Key for hip stability and pelvic floor support'],
              yt: 'inner outer thigh machine technique',
            },
            {
              id: 'D1-s3', name: 'Seated Calf Raise',
              prescription: '3 x 20', sets: 3, reps: 20,
              note: 'Full range, pause at top. POTS: therapeutic calf pump — venous return.',
              muscles: 'Soleus · Gastrocnemius',
              cues: ['Rise as high as possible', 'Pause at the top for 1 second', 'Lower fully — feel the stretch at bottom', 'POTS: the calf is a second heart — this is therapeutic, not optional'],
              yt: 'seated calf raise POTS venous return',
            },
          ],
        },
        {
          id: 'D1-cooldown',
          type: 'cardio',
          bodyPart: 'Cool-Down',
          icon: '❄️',
          duration: '5 min',
          exercises: [
            {
              id: 'D1-cd1a', name: 'Recumbent Bike',
              prescription: '1 x 3–5 min', sets: 1, reps: 1,
              note: 'PRIMARY - Very low resistance. POTS: let HR drop naturally before standing.',
              muscles: 'Cardiovascular recovery · Calf pump',
              cues: ['Lowest possible resistance', 'Let HR come down naturally — do not rush', 'POTS: stay seated 10–15 sec after stopping'],
              yt: 'recumbent bike cool down',
            },
            {
              id: 'D1-cd1b', name: 'Rower',
              prescription: '1 x 3–5 min', sets: 1, reps: 1,
              note: 'Alt 1 - Very easy pace, damper 2. Seated cool-down option.',
              muscles: 'Cardiovascular recovery',
              cues: ['Damper 2, very easy pace', 'Focus on breathing, not effort', 'Remain seated until HR is calm'],
              yt: 'rowing machine cool down',
            },
            {
              id: 'D1-cd1c', name: 'Treadmill (Incline Walk)',
              prescription: '1 x 3–5 min', sets: 1, reps: 1,
              note: 'Alt 2 - Flat or 2%, very slow. POTS: hold rails, pause before stepping off.',
              muscles: 'Cardiovascular recovery',
              cues: ['Flat or 2% incline, slowest walking pace', 'POTS: hold rails', 'POTS: pause on belt for 10 sec before stepping off'],
              yt: 'treadmill cool down walk',
            },
            {
              id: 'D1-cd2', name: 'Legs-Up-the-Wall / Feet Elevated',
              prescription: '1 x 2–3 min', sets: 1, reps: 1,
              note: 'POTS: venous return post-session. Feet on bench or wall.',
              muscles: 'Venous return · Lower back decompression',
              cues: ['Lie on mat, feet on bench or wall', 'Arms relaxed, palms up', 'Slow breathing — let body recover', 'POTS: rise slowly when finished'],
              yt: 'legs up wall recovery POTS',
              bodyweight: true,
            },
          ],
        },
      ],
    },

    /* ── D2 · Upper Body ── */
    {
      id: 'D2',
      name: 'Upper Body',
      type: 'training',
      duration: 50,
      note: 'Right scapula — monitor all pulling and pressing. Reduce range or load on right side if any discomfort. hEDS — no elbow or shoulder lockout.',
      blocks: [
        {
          id: 'D2-warmup',
          type: 'warmup',
          bodyPart: 'Warm-Up',
          icon: '🔥',
          duration: '8 min',
          exercises: [
            {
              id: 'D2-w1a', name: 'Recumbent Bike',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'PRIMARY - Low resistance. POTS: preferred warm-up — back supported, no orthostatic stress.',
              muscles: 'Cardiovascular warm-up',
              cues: ['Low resistance, easy pace', 'POTS: best warm-up option — fully supported', 'Rise slowly after'],
              yt: 'recumbent bike warm up',
            },
            {
              id: 'D2-w1b', name: 'Rower',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 1 - Easy pace, damper 3–4. Right scapula: reduce range if pull discomfort.',
              muscles: 'Cardiovascular warm-up · Back warm-up',
              cues: ['Easy pace, damper 3–4', 'Right scapula: if any pull discomfort, reduce range of drive', 'Good seated POTS alternative'],
              yt: 'rowing machine warm up technique',
            },
            {
              id: 'D2-w1c', name: 'Treadmill (Incline Walk)',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 2 - 4–6% incline, slow pace. POTS: hold rails.',
              muscles: 'Cardiovascular warm-up',
              cues: ['4–6% incline, slow pace', 'POTS: hold rails', 'Good posture warm-up for upper body day'],
              yt: 'treadmill incline walk posture',
            },
            {
              id: 'D2-w1d', name: 'Stairmaster',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 3 - Low speed. POTS: hold rails. Skip on high-symptom days.',
              muscles: 'Cardiovascular warm-up',
              cues: ['Lowest comfortable speed', 'POTS: hold rails throughout', 'Skip on high-symptom days'],
              yt: 'stairmaster low intensity warm up',
            },
            {
              id: 'D2-w2', name: 'Shoulder Rolls + Neck Tilts',
              prescription: '1 x 10', sets: 1, reps: 10,
              note: 'Each direction, seated. Right scapula: comfortable range only.',
              muscles: 'Shoulder girdle · Cervical spine mobilisation',
              cues: ['Slow full rolls forward then backward', 'Neck tilts: ear toward shoulder, hold 3 sec', 'Right scapula: notice any pull or pinch — stay in comfortable range'],
              yt: 'shoulder rolls neck tilts upper body warm up',
              bodyweight: true,
            },
            {
              id: 'D2-w3', name: 'Band Face Pulls / Scapula Retractions',
              prescription: '2 x 15', sets: 2, reps: 15,
              note: 'Light resistance. Right shoulder: reduce range if needed.',
              muscles: 'Posterior deltoid · Rhomboids · Rotator cuff',
              cues: ['Light band — this is activation not loading', 'Pull to face, elbows flared', 'Right shoulder: if pinch or pull, reduce range of motion', 'Focus on squeezing shoulder blades together'],
              yt: 'face pull band scapula activation',
              bodyweight: true,
            },
          ],
        },
        {
          id: 'D2-main',
          type: 'main',
          bodyPart: 'Back',
          icon: '💪',
          duration: '22 min',
          exercises: [
            {
              id: 'D2-m1', name: 'Lat Pull-Down (Cable)',
              prescription: '3 x 10–12', sets: 3, reps: 12,
              note: 'Pull to chin — never behind neck. hEDS: keep slight elbow bend. Right scapula: monitor.',
              muscles: 'Latissimus dorsi · Teres major · Biceps',
              cues: ['Pull bar to chin level — never behind neck', 'hEDS: keep a slight bend in elbows at top — do not lock out', 'Lean back slightly (10–15°), chest up', 'Right scapula: if any discomfort, reduce weight or range on right side'],
              yt: 'lat pulldown cable form technique',
            },
            {
              id: 'D2-m2', name: 'Low Row Machine',
              prescription: '3 x 10–12', sets: 3, reps: 12,
              note: 'Chest up, slow 3-sec eccentric. Squeeze shoulder blades. Right side: reduce if discomfort.',
              muscles: 'Mid-back · Rhomboids · Latissimus dorsi · Biceps',
              cues: ['Sit tall, chest up throughout', 'Squeeze shoulder blades together at the end of each rep', 'Slow eccentric — 3 sec returning forward', 'Right side: reduce load or range if any shoulder blade discomfort'],
              yt: 'seated row machine technique',
            },
            {
              id: 'D2-m3', name: 'High Row (Plate Load)',
              prescription: '3 x 12', sets: 3, reps: 12,
              note: 'Drive elbows toward back pockets. Right scapula: monitor throughout.',
              muscles: 'Upper back · Posterior deltoid · Rhomboids',
              cues: ['Drive elbows back and down — toward back pockets', 'Keep torso upright', 'Right scapula: monitor for any discomfort — reduce if needed', 'Controlled lowering'],
              yt: 'high row plate loaded back exercise',
            },
          ],
        },
        {
          id: 'D2-prehab',
          type: 'prehab',
          bodyPart: 'Chest & Shoulders',
          icon: '🏋️',
          duration: '15 min',
          exercises: [
            {
              id: 'D2-s1', name: 'Seated Chest Press Machine',
              prescription: '3 x 10–12', sets: 3, reps: 12,
              note: 'hEDS: stop just short of elbow lockout. Machine path safer than free bar.',
              muscles: 'Pectorals · Anterior deltoid · Triceps',
              cues: ['hEDS: stop just before elbows fully straighten — maintain slight bend', 'Back pressed into pad throughout', 'Controlled tempo both ways — no bouncing', 'Machine is safer than barbell for hypermobile joints'],
              yt: 'chest press machine form technique',
            },
            {
              id: 'D2-s2', name: 'Pec Fly Machine',
              prescription: '3 x 12–15', sets: 3, reps: 15,
              note: 'hEDS: stop at gentle tension — not full pec stretch. Avoid end-range.',
              muscles: 'Pectorals · Anterior deltoid',
              cues: ['hEDS: stop when you feel gentle tension — well before end range', 'Think of hugging a barrel — not pulling arms apart', 'Slow and controlled on the way back', 'Do not let the weight pull your shoulders back past comfortable'],
              yt: 'pec fly machine form hypermobility',
            },
            {
              id: 'D2-s3', name: 'Shoulder Press Machine',
              prescription: '3 x 10–12', sets: 3, reps: 12,
              note: 'hEDS: stop just short of lockout at top. Seated machine preferred.',
              muscles: 'Deltoids · Trapezius · Triceps',
              cues: ['hEDS: stop just before elbows lock out at top', 'Seat height: handles at shoulder level', 'Press smoothly — no jerking', 'Controlled lowering to start position'],
              yt: 'shoulder press machine seated technique',
            },
            {
              id: 'D2-s4', name: 'Rear Delt Fly (Pec Fly Machine)',
              prescription: '2 x 15', sets: 2, reps: 15,
              note: 'Lead with elbows. Right scapula: comfortable range only.',
              muscles: 'Posterior deltoid · Rhomboids · Rotator cuff',
              cues: ['Use reverse setting on pec fly machine', 'Lead with elbows, slight bend maintained', 'Right scapula: stay within comfortable range', 'This is a stability exercise — use light weight with control'],
              yt: 'rear delt fly pec deck machine',
            },
          ],
        },
        {
          id: 'D2-cooldown',
          type: 'cardio',
          bodyPart: 'Cool-Down',
          icon: '❄️',
          duration: '5 min',
          exercises: [
            {
              id: 'D2-cd1a', name: 'Recumbent Bike',
              prescription: '1 x 3 min', sets: 1, reps: 1,
              note: 'PRIMARY - Very low resistance. POTS: HR recovery before standing.',
              muscles: 'Cardiovascular recovery',
              cues: ['Lowest resistance', 'POTS: wait for HR to settle before standing', 'Rise slowly'],
              yt: 'recumbent bike cool down recovery',
            },
            {
              id: 'D2-cd1b', name: 'Rower',
              prescription: '1 x 3 min', sets: 1, reps: 1,
              note: 'Alt 1 - Very easy, damper 2. Seated cool-down option.',
              muscles: 'Cardiovascular recovery',
              cues: ['Damper 2, minimal effort', 'Breathe slowly', 'Seated recovery option'],
              yt: 'rowing machine cool down recovery',
            },
            {
              id: 'D2-cd1c', name: 'Treadmill (Incline Walk)',
              prescription: '1 x 3 min', sets: 1, reps: 1,
              note: 'Alt 2 - Flat or 2%, very slow. POTS: hold rails, pause before stepping off.',
              muscles: 'Cardiovascular recovery',
              cues: ['Flat or minimal incline, very slow pace', 'POTS: hold rails', 'Pause on belt 10 sec before stepping off'],
              yt: 'treadmill slow walk cool down',
            },
            {
              id: 'D2-cd2', name: 'Seated Cross-Body Shoulder Stretch',
              prescription: '1 x 45 sec each', sets: 1, reps: 1,
              note: 'hEDS: hold at first tension — no aggressive pulling. Right shoulder: extra care.',
              muscles: 'Posterior deltoid · Rhomboids stretch',
              cues: ['Arm across chest at shoulder height', 'hEDS: stop at first gentle tension — no pulling', 'Right shoulder: be especially gentle', 'Breathe slowly and hold'],
              yt: 'cross body shoulder stretch technique',
              bodyweight: true,
            },
          ],
        },
      ],
    },

    /* ── D3 · Full Rest ── */
    {
      id: 'D3',
      name: 'Full Rest',
      type: 'rest',
      duration: 0,
      note: 'Full rest day. Gentle walk fine — no structured exercise.',
      blocks: [],
    },

    /* ── D4 · Hip & Core ── */
    {
      id: 'D4',
      name: 'Hip & Core',
      type: 'training',
      duration: 50,
      note: 'Hip thrust second session this week — intentional for glute stimulus and pregnancy prep. Core work includes pelvic floor awareness.',
      blocks: [
        {
          id: 'D4-warmup',
          type: 'warmup',
          bodyPart: 'Warm-Up',
          icon: '🔥',
          duration: '8 min',
          exercises: [
            {
              id: 'D4-w1a', name: 'Recumbent Bike',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'PRIMARY - Low resistance. POTS: back supported warm-up. Rise slowly after.',
              muscles: 'Cardiovascular warm-up',
              cues: ['Low resistance, easy pace', 'POTS: back fully supported', 'Rise slowly after stopping'],
              yt: 'recumbent bike warm up POTS',
            },
            {
              id: 'D4-w1b', name: 'Rower',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 1 - Easy pace, damper 3–4. Seated — good POTS option.',
              muscles: 'Cardiovascular warm-up',
              cues: ['Easy pace, damper 3–4', 'Good seated POTS option', 'Controlled rowing — no explosive drive'],
              yt: 'rowing machine easy warm up',
            },
            {
              id: 'D4-w1c', name: 'Treadmill (Incline Walk)',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 2 - 4–6% incline, slow pace. POTS: hold rails if needed.',
              muscles: 'Cardiovascular warm-up · Glutes activation',
              cues: ['4–6% incline, slow walking pace', 'POTS: hold rails if unsteady', 'Good glute pre-activation for hip session'],
              yt: 'treadmill incline walk glute activation',
            },
            {
              id: 'D4-w1d', name: 'Stairmaster',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 3 - Low speed. POTS: hold rails. Skip on high-symptom days.',
              muscles: 'Cardiovascular warm-up · Glutes · Quads',
              cues: ['Lowest comfortable speed', 'POTS: hold rails throughout', 'Skip on high-symptom days'],
              yt: 'stairmaster beginner low speed',
            },
            {
              id: 'D4-w2', name: 'Seated Hip Circles',
              prescription: '1 x 10', sets: 1, reps: 10,
              note: 'Each direction, seated in chair. Bodyweight.',
              muscles: 'Hip joint mobilisation · Hip flexors · Glutes',
              cues: ['Seated, hands on thighs for support', 'Draw large slow circles with the hip', 'Both directions — 10 each', 'hEDS: comfortable range only'],
              yt: 'seated hip circles mobility warm up',
              bodyweight: true,
            },
            {
              id: 'D4-w3', name: 'Ankle Pumps + Calf Raises (Standing)',
              prescription: '1 x 20 pumps + 15 raises', sets: 1, reps: 20,
              note: 'POTS: activate calf pump. Hold rail if unsteady.',
              muscles: 'Calf pump · Ankle stabilisers',
              cues: ['Hold rail for balance', 'Pumps: flex and point foot slowly', 'Calf raises: rise onto toes, pause, lower slowly', 'POTS: activates venous return before training'],
              yt: 'calf raises standing calf pump',
              bodyweight: true,
            },
          ],
        },
        {
          id: 'D4-main',
          type: 'main',
          bodyPart: 'Glutes & Hips',
          icon: '🍑',
          duration: '22 min',
          exercises: [
            {
              id: 'D4-m1', name: 'Hip Thrust Machine',
              prescription: '4 x 12–15', sets: 4, reps: 15,
              note: 'Slow squeeze at top. hEDS: stop at neutral hip. Second session — key for pregnancy prep.',
              muscles: 'Glutes (max activation) · Hamstrings',
              cues: ['Drive through heels', 'hEDS: stop when hips are level with torso — do not push further into hyperextension', 'Hold squeeze at top for 1 sec', '4 sets this session — this is the key pregnancy prep exercise'],
              yt: 'hip thrust machine glute pregnancy prep',
            },
            {
              id: 'D4-m2', name: 'Cable Hip Abduction',
              prescription: '3 x 15 each', sets: 3, reps: 15,
              note: 'Controlled range — no hip hiking. Gluteus medius + pelvic stability.',
              muscles: 'Gluteus medius · TFL · Hip abductors',
              cues: ['Hold cable machine for balance', 'hEDS: controlled arc — do not swing or hike hip', 'Slow return — do not let cable pull you', 'Key for pelvic stability and pregnancy prep'],
              yt: 'cable hip abduction glute med technique',
            },
            {
              id: 'D4-m3', name: 'Inner / Outer Thigh Machine',
              prescription: '3 x 15', sets: 3, reps: 15,
              note: 'Each direction. Hip stability + adductor/abductor balance.',
              muscles: 'Adductors (inner) · Abductors / Gluteus medius (outer)',
              cues: ['Both directions in one sitting — switch pin', 'Slow and controlled — no slamming weight', 'hEDS: comfortable range', 'Important for pelvic floor and hip stability'],
              yt: 'inner outer thigh machine hip stability',
            },
          ],
        },
        {
          id: 'D4-prehab',
          type: 'prehab',
          bodyPart: 'Core & Stability',
          icon: '⚡',
          duration: '18 min',
          exercises: [
            {
              id: 'D4-s1', name: 'Abdominal Machine (Crunch)',
              prescription: '3 x 12–15', sets: 3, reps: 15,
              note: 'hEDS: machine guides ROM. Pelvic floor: engage gently — no breath-holding.',
              muscles: 'Rectus abdominis · Obliques',
              cues: ['hEDS: machine controls range — do not force beyond comfortable', 'Exhale on crunch, inhale on return', 'Pelvic floor: gentle engagement — no breath-holding or bearing down', 'Slow controlled movement both ways'],
              yt: 'ab crunch machine core technique',
            },
            {
              id: 'D4-s2', name: 'Rotary Torso Machine',
              prescription: '3 x 12 each', sets: 3, reps: 12,
              note: 'Comfortable rotation range only — hEDS: never force end-range.',
              muscles: 'Obliques · Transverse abdominis · Spinal rotators',
              cues: ['hEDS: rotate only to comfortable range — stop before any pull or strain', 'Slow and controlled both ways', 'Keep hips still — rotation comes from torso only', 'Exhale on rotation'],
              yt: 'rotary torso machine obliques technique',
            },
            {
              id: 'D4-s3', name: 'Seated Calf Raise',
              prescription: '3 x 20', sets: 3, reps: 20,
              note: 'POTS: second calf session. Therapeutic venous return. Pause at top.',
              muscles: 'Soleus · Gastrocnemius',
              cues: ['Rise as high as possible, pause at top', 'Lower fully through full range', 'POTS: second therapeutic calf session this week — this is important', 'Slow pace — feel the pump'],
              yt: 'seated calf raise venous return therapeutic',
            },
            {
              id: 'D4-s4', name: 'Seated Back Extension (Bodyweight)',
              prescription: '2 x 12', sets: 2, reps: 12,
              note: 'Bodyweight only. hEDS: stop at neutral — no hyperextension past straight.',
              muscles: 'Erector spinae · Glutes · Hamstrings',
              cues: ['Bodyweight only — no added load for now', 'hEDS: extend only to neutral (flat back) — never arch further', 'Slow controlled movement', 'Breathe out on extension'],
              yt: 'back extension machine neutral spine technique',
              bodyweight: true,
            },
          ],
        },
        {
          id: 'D4-cooldown',
          type: 'cardio',
          bodyPart: 'Cool-Down',
          icon: '❄️',
          duration: '5 min',
          exercises: [
            {
              id: 'D4-cd1a', name: 'Recumbent Bike',
              prescription: '1 x 3 min', sets: 1, reps: 1,
              note: 'PRIMARY - Very low resistance. POTS: pause 10–15 sec before leaving the bike.',
              muscles: 'Cardiovascular recovery',
              cues: ['Lowest resistance', 'POTS: stay in seat for 10–15 sec after stopping', 'Rise slowly'],
              yt: 'recumbent bike cool down',
            },
            {
              id: 'D4-cd1b', name: 'Rower',
              prescription: '1 x 3 min', sets: 1, reps: 1,
              note: 'Alt 1 - Very easy, damper 2. Seated cool-down option.',
              muscles: 'Cardiovascular recovery',
              cues: ['Damper 2, minimal effort', 'Breathe slowly, let HR come down'],
              yt: 'rowing machine easy cool down',
            },
            {
              id: 'D4-cd1c', name: 'Treadmill (Incline Walk)',
              prescription: '1 x 3 min', sets: 1, reps: 1,
              note: 'Alt 2 - Flat or 2%, very slow. POTS: hold rails, pause before stepping off.',
              muscles: 'Cardiovascular recovery',
              cues: ['Flat or 2%, very slow', 'POTS: hold rails', 'Pause on belt before stepping off'],
              yt: 'treadmill slow walk cool down',
            },
            {
              id: 'D4-cd2', name: 'Legs-Up-the-Wall / Feet Elevated',
              prescription: '1 x 2–3 min', sets: 1, reps: 1,
              note: 'POTS: post-session venous return. Feet on bench or wall.',
              muscles: 'Venous return · Lower back decompression',
              cues: ['Feet on bench or up against wall', 'Arms relaxed', 'Slow breathing', 'POTS: rise slowly when finished'],
              yt: 'legs up wall venous return recovery',
              bodyweight: true,
            },
          ],
        },
      ],
    },

    /* ── D5 · Cardio ── */
    {
      id: 'D5',
      name: 'Cardio',
      type: 'cardio_day',
      duration: 45,
      commute: false,
      note: 'Block B is optional — skip on high-symptom days. Recumbent bike preferred — no upright bike until cleared by GP or Physio/Osteo.',
      blocks: [
        {
          id: 'D5-warmup',
          type: 'warmup',
          bodyPart: 'Warm-Up',
          icon: '🔥',
          duration: '7 min',
          exercises: [
            {
              id: 'D5-w1a', name: 'Recumbent Bike',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'PRIMARY - Very easy, low resistance. POTS: preferred — back supported.',
              muscles: 'Cardiovascular warm-up',
              cues: ['Very easy, low resistance', 'POTS: preferred option — back fully supported', 'Rise slowly after'],
              yt: 'recumbent bike warm up easy',
            },
            {
              id: 'D5-w1b', name: 'Rower',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 1 - Very easy, damper 3. Seated — good POTS alternative.',
              muscles: 'Cardiovascular warm-up',
              cues: ['Damper 3, very easy', 'Seated POTS-safe option', 'Smooth controlled rowing'],
              yt: 'rowing machine easy pace warm up',
            },
            {
              id: 'D5-w1c', name: 'Treadmill (Incline Walk)',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 2 - 4–6% incline, slow pace. POTS: hold rails.',
              muscles: 'Cardiovascular warm-up',
              cues: ['4–6% incline, slow pace', 'POTS: hold rails', 'Good alternative if recumbent is occupied'],
              yt: 'treadmill incline walk warm up',
            },
            {
              id: 'D5-w1d', name: 'Stairmaster',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 3 - Low speed. POTS: hold rails. Skip on high-symptom days.',
              muscles: 'Cardiovascular warm-up · Glutes',
              cues: ['Lowest speed', 'POTS: hold rails at all times', 'Skip on high-symptom days'],
              yt: 'stairmaster beginner technique',
            },
            {
              id: 'D5-w2', name: 'Seated Ankle Rolls + Calf Pumps',
              prescription: '1 x 15', sets: 1, reps: 15,
              note: 'POTS: calf pump activation before cardio.',
              muscles: 'Calf pump · Ankle stabilisers',
              cues: ['Circles each direction', 'Then flex-point 15 times', 'POTS: essential before any sustained cardio'],
              yt: 'ankle rolls calf pumps seated warm up',
              bodyweight: true,
            },
            {
              id: 'D5-w3', name: 'Seated Arm Circles + Shoulder Rolls',
              prescription: '1 x 10', sets: 1, reps: 10,
              note: 'Upper body warm-up while seated.',
              muscles: 'Shoulder girdle mobilisation',
              cues: ['Large slow circles both directions', 'Shoulder rolls: up, back, down', 'Seated throughout'],
              yt: 'arm circles shoulder rolls seated warm up',
              bodyweight: true,
            },
          ],
        },
        {
          id: 'D5-blockA',
          type: 'cardio',
          bodyPart: 'Steady State',
          icon: '🚴',
          duration: '15 min',
          exercises: [
            {
              id: 'D5-cA', name: 'Recumbent Bike — Steady State',
              prescription: '1 x 15 min', sets: 1, reps: 1,
              note: 'PRIMARY - Zone 2 · HR below 120 bpm · 70–80 RPM. POTS: stop if dizzy, slow if HR rising too fast.',
              muscles: 'Cardiovascular conditioning · Quads · Calves',
              cues: ['HR below 120 bpm throughout', '70–80 RPM cadence', 'You should be able to hold a conversation', 'POTS: if HR spikes or dizziness — reduce resistance immediately', 'POTS: this is the most important POTS-safe cardio session of the week'],
              yt: 'recumbent bike zone 2 cardio POTS',
            },
          ],
        },
        {
          id: 'D5-blockB',
          type: 'cardio',
          bodyPart: 'Light Intervals (optional)',
          icon: '💓',
          duration: '12 min',
          note: 'Skip this entire block on high-symptom days.',
          exercises: [
            {
              id: 'D5-cB', name: 'Recumbent Bike — Easy Intervals',
              prescription: '1 x 12 min', sets: 1, reps: 1,
              note: 'PRIMARY - 2 min easy / 1 min slightly harder ×4. POTS: skip on high-symptom days. HR never above 125 bpm.',
              muscles: 'Cardiovascular conditioning',
              cues: ['POTS: skip this block entirely on high-symptom days', '2 min easy — 1 min slightly harder — repeat 4 times', 'Harder = raise resistance 1–2 levels only', 'HR must stay below 125 bpm at all times', 'If HR approaches 125 — drop back to easy immediately'],
              yt: 'recumbent bike intervals gentle POTS safe',
            },
          ],
        },
        {
          id: 'D5-cooldown',
          type: 'cardio',
          bodyPart: 'Cool-Down',
          icon: '❄️',
          duration: '8 min',
          exercises: [
            {
              id: 'D5-cd1a', name: 'Recumbent Bike',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'PRIMARY - Very low resistance. POTS: HR under 100 before standing.',
              muscles: 'Cardiovascular recovery',
              cues: ['Lowest resistance', 'POTS: wait until HR is below 100 before standing', 'Stay seated — do not rush'],
              yt: 'recumbent bike cool down recovery',
            },
            {
              id: 'D5-cd1b', name: 'Rower',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 1 - Very easy, damper 2. Seated cool-down option.',
              muscles: 'Cardiovascular recovery',
              cues: ['Damper 2, very easy', 'Breathe and recover', 'Seated — good POTS option'],
              yt: 'rowing machine easy cool down',
            },
            {
              id: 'D5-cd1c', name: 'Treadmill (Incline Walk)',
              prescription: '1 x 5 min', sets: 1, reps: 1,
              note: 'Alt 2 - Flat, very slow. POTS: hold rails, pause before stepping off.',
              muscles: 'Cardiovascular recovery',
              cues: ['Flat, very slow pace', 'POTS: hold rails', 'Pause on belt before stepping off'],
              yt: 'treadmill slow walk cool down',
            },
            {
              id: 'D5-cd2', name: 'Seated Calf Raises',
              prescription: '1 x 20', sets: 1, reps: 20,
              note: 'POTS: calf pump while still seated.',
              muscles: 'Calf pump · Venous return',
              cues: ['While still seated after cardio', 'Full range — rise high, lower fully', 'POTS: keeps venous return active before standing'],
              yt: 'seated calf raise venous return post cardio',
              bodyweight: true,
            },
            {
              id: 'D5-cd3', name: 'Feet Elevated Rest',
              prescription: '1 x 3 min', sets: 1, reps: 1,
              note: 'POTS: lie back, feet on bench. Let circulation settle.',
              muscles: 'Venous return · Recovery',
              cues: ['Lie back, feet on bench or elevated', 'Arms relaxed, slow breathing', 'POTS: lets blood pool drain from legs', 'Rise slowly when finished'],
              yt: 'supine feet elevated recovery POTS',
              bodyweight: true,
            },
          ],
        },
      ],
    },

    /* ── D6 · Stretching & Yoga ── */
    {
      id: 'D6',
      name: 'Stretching & Yoga',
      type: 'stretch',
      duration: 55,
      note: 'POTS — legs-up-the-wall at close is essential, not optional. hEDS — hold at first tension, never force range.',
      yogaLog: {
        durationOptions: [30, 40, 55, 70],
        styleOptions: ['Full session', 'Stretch focus', 'Yoga flow', 'Pelvic floor & core', 'Gentle / low-symptom day'],
      },
      blocks: [
        {
          id: 'D6-opening',
          type: 'warmup',
          bodyPart: 'Opening',
          icon: '🌅',
          duration: '8 min',
          logType: 'session',
          exercises: [
            {
              id: 'D6-p1a', name: 'Diaphragmatic Breathing',
              prescription: '1 x 3 min', sets: 1, reps: 1,
              note: 'POTS: activates parasympathetic — good for symptom management.',
              muscles: 'Diaphragm · Parasympathetic activation',
              cues: ['4s inhale through nose', 'Hold 2s', '6s exhale through mouth', 'POTS: this calms the autonomic nervous system — take your time'],
              yt: 'diaphragmatic breathing POTS dysautonomia',
              bodyweight: true,
            },
            {
              id: 'D6-p1b', name: 'Neck Tilts + Gentle Rolls',
              prescription: '1 x 5 each side', sets: 1, reps: 5,
              note: 'hEDS: avoid rolling head fully back — side to front only.',
              muscles: 'Cervical spine · Upper trapezius',
              cues: ['Ear toward shoulder, hold 3 sec', 'hEDS: half circles only — ear to ear via chin, not via back of head', 'Slow and gentle', 'If any dizziness — stop and breathe'],
              yt: 'neck stretches gentle hypermobility safe',
              bodyweight: true,
            },
            {
              id: 'D6-p1c', name: 'Seated Torso Rotations',
              prescription: '1 x 8 each side', sets: 1, reps: 8,
              note: 'hEDS: comfortable range only. Hold 2s each.',
              muscles: 'Thoracic spine · Obliques',
              cues: ['Sit tall, hands on opposite shoulders', 'Rotate gently to comfortable range', 'hEDS: stop well before end-range — no overpressure', 'Hold 2 sec each side'],
              yt: 'seated torso rotation mobility stretch',
              bodyweight: true,
            },
            {
              id: 'D6-p1d', name: 'Seated Side Reach',
              prescription: '1 x 8 each side', sets: 1, reps: 8,
              note: 'Hold 3s each side.',
              muscles: 'Lateral trunk · Quadratus lumborum',
              cues: ['Sit tall, reach one arm overhead and lean', 'Feel the side-body lengthen', 'hEDS: comfortable range — no pulling', 'Hold 3 sec'],
              yt: 'seated side reach lateral stretch',
              bodyweight: true,
            },
          ],
        },
        {
          id: 'D6-lower',
          type: 'main',
          bodyPart: 'Lower Body',
          icon: '🦵',
          duration: '18 min',
          exercises: [
            {
              id: 'D6-p2a', name: 'Hip Flexor Stretch (Supported)',
              prescription: '1 x 45 sec each', sets: 1, reps: 1,
              note: 'Chair or rail for balance. hEDS: gentle — not end-range.',
              muscles: 'Hip flexors · Psoas · Iliacus',
              cues: ['One foot forward, rear knee down or extended', 'Hold chair or rail for balance', 'hEDS: gentle lean forward — stop at first stretch sensation, not end-range', 'Important for pelvic posture and pregnancy prep'],
              yt: 'hip flexor stretch standing supported',
              bodyweight: true,
            },
            {
              id: 'D6-p2b', name: 'Pigeon Pose (Chair Modified)',
              prescription: '1 x 60 sec each', sets: 1, reps: 1,
              note: 'Seated modification — foot on opposite knee. hEDS: no deep floor pigeon.',
              muscles: 'Glutes · Piriformis · External hip rotators',
              cues: ['Seated: cross ankle over opposite knee', 'Sit tall or hinge gently forward', 'hEDS: no pushing knee down — let gravity work', 'hEDS: avoid full floor pigeon which risks end-range hip loading'],
              yt: 'chair pigeon pose hip stretch seated',
              bodyweight: true,
            },
            {
              id: 'D6-p2c', name: 'Standing Quad Stretch',
              prescription: '1 x 45 sec each', sets: 1, reps: 1,
              note: 'Hold wall. hEDS: hold at gentle tension only.',
              muscles: 'Quadriceps · Hip flexors',
              cues: ['Hold wall with one hand', 'Bend knee and hold ankle behind you', 'hEDS: stop at gentle tension — do not pull heel aggressively toward glute', 'Keep knees together'],
              yt: 'standing quad stretch hypermobility safe',
              bodyweight: true,
            },
            {
              id: 'D6-p2d', name: 'Standing Hamstring Stretch (Supported)',
              prescription: '1 x 45 sec each', sets: 1, reps: 1,
              note: 'Foot on low step. hEDS: neutral spine throughout — never round.',
              muscles: 'Hamstrings · Posterior chain',
              cues: ['Rest heel on low bench or step', 'Hinge forward from hips — not waist', 'hEDS: neutral spine throughout — never round the lower back', 'hEDS: stop at gentle tension, not end-range'],
              yt: 'hamstring stretch standing supported neutral spine',
              bodyweight: true,
            },
            {
              id: 'D6-p2e', name: 'Seated Calf Stretch',
              prescription: '1 x 45 sec each', sets: 1, reps: 1,
              note: 'hEDS: gentle dorsiflexion. POTS: venous return benefit.',
              muscles: 'Gastrocnemius · Soleus',
              cues: ['Seated, foot flat on floor — lean forward gently', 'hEDS: gentle dorsiflexion only — do not force ankle end-range', 'POTS: calf flexibility supports venous pump function'],
              yt: 'seated calf stretch gentle technique',
              bodyweight: true,
            },
          ],
        },
        {
          id: 'D6-upper',
          type: 'prehab',
          bodyPart: 'Upper Body',
          icon: '💪',
          duration: '12 min',
          exercises: [
            {
              id: 'D6-p3a', name: 'Cross-Body Shoulder Stretch',
              prescription: '1 x 45 sec each', sets: 1, reps: 1,
              note: 'hEDS: hold at first tension only. Right shoulder: extra care.',
              muscles: 'Posterior deltoid · Rhomboids',
              cues: ['Arm across chest at shoulder height', 'Opposite hand on elbow — gentle hold only', 'hEDS: stop at first tension — no pulling', 'Right shoulder: be especially gentle'],
              yt: 'cross body shoulder stretch gentle',
              bodyweight: true,
            },
            {
              id: 'D6-p3b', name: 'Chest Opener (Doorframe or Wall)',
              prescription: '1 x 45 sec', sets: 1, reps: 1,
              note: 'Arms at 90°. hEDS: gentle — no forced range.',
              muscles: 'Pectorals · Anterior deltoid',
              cues: ['Forearms on doorframe or flat against wall', 'Gentle lean forward', 'hEDS: stop at first stretch — no leaning aggressively into it', 'Good for POTS posture correction'],
              yt: 'chest opener doorframe stretch gentle',
              bodyweight: true,
            },
            {
              id: 'D6-p3c', name: 'Lat Stretch (Hand on Wall)',
              prescription: '1 x 30 sec each', sets: 1, reps: 1,
              note: 'Comfortable range.',
              muscles: 'Latissimus dorsi · Teres major',
              cues: ['One hand on wall above head', 'Lean body away to feel lat stretch', 'hEDS: comfortable range only', 'Breathe slowly and hold'],
              yt: 'lat stretch wall standing',
              bodyweight: true,
            },
            {
              id: 'D6-p3d', name: 'Wrist + Hand Stretches',
              prescription: '1 x 30 sec each direction', sets: 1, reps: 1,
              note: 'hEDS: gentle joint mobility — important for hypermobile wrists/fingers.',
              muscles: 'Wrist extensors · Flexors · Finger joints',
              cues: ['hEDS: very gentle — hypermobile joints need mobility work without overstress', 'Palm down, gentle downward pressure', 'Palm up, gentle downward pressure', 'Fingers back, gentle pressure — stop before discomfort'],
              yt: 'wrist hand stretches hypermobility EDS',
              bodyweight: true,
            },
          ],
        },
        {
          id: 'D6-core',
          type: 'prehab',
          bodyPart: 'Core & Pelvic Floor',
          icon: '🧘',
          duration: '10 min',
          exercises: [
            {
              id: 'D6-p4a', name: 'Pelvic Floor Engagement',
              prescription: '1 x 10 x 5s holds', sets: 1, reps: 10,
              note: 'Pregnancy prep: inhale to prepare, exhale to gently lift. No breath-holding or gripping.',
              muscles: 'Pelvic floor · Deep core',
              cues: ['Seated comfortably', 'Inhale to prepare', 'Exhale and gently lift pelvic floor — think elevator going up slowly', 'Hold 5 sec, breathe throughout — no breath-holding', 'No gripping or bearing down', 'Pregnancy prep: this is foundational — do every session'],
              yt: 'pelvic floor exercise seated pregnancy prep',
              bodyweight: true,
            },
            {
              id: 'D6-p4b', name: 'Cat-Cow (Seated on Chair)',
              prescription: '1 x 10', sets: 1, reps: 10,
              note: 'hEDS: very small range — no deep arch or deep flex.',
              muscles: 'Spinal extensors · Multifidus · Abdominals',
              cues: ['Seated, hands on knees', 'hEDS: very small range — a few degrees each way', 'Inhale into gentle extension, exhale into gentle flexion', 'This is mobility, not stretch — do not push range'],
              yt: 'seated cat cow chair hypermobility safe',
              bodyweight: true,
            },
            {
              id: 'D6-p4c', name: 'Seated Glute Stretch (Figure 4)',
              prescription: '1 x 60 sec each', sets: 1, reps: 1,
              note: 'hEDS: let gravity do the work — no pushing knee down.',
              muscles: 'Glutes · Piriformis · External hip rotators',
              cues: ['Cross ankle over opposite knee', 'Sit tall and let gravity pull the knee down', 'hEDS: never push the knee down with your hand', 'Hold and breathe'],
              yt: 'figure four seated stretch glutes',
              bodyweight: true,
            },
          ],
        },
        {
          id: 'D6-closing',
          type: 'cardio',
          bodyPart: 'Closing',
          icon: '☮️',
          duration: '7 min',
          exercises: [
            {
              id: 'D6-p5a', name: 'Legs-Up-the-Wall',
              prescription: '1 x 3–5 min', sets: 1, reps: 1,
              note: 'PRIMARY - POTS: essential close — powerful venous return.',
              muscles: 'Venous return · Parasympathetic recovery',
              cues: ['Lie on floor or mat, swing legs up wall', 'Arms relaxed by sides, palms up', 'Slow breathing throughout', 'POTS: this is the single most effective venous return position', 'POTS: rise slowly — roll to side first, pause seated before standing'],
              yt: 'legs up wall POTS recovery venous return',
              bodyweight: true,
            },
            {
              id: 'D6-p5b', name: 'Closing Breathing',
              prescription: '1 x 3 min', sets: 1, reps: 1,
              note: 'Alt 1 - 4s inhale, 8s exhale. POTS: nervous system regulation.',
              muscles: 'Diaphragm · Parasympathetic activation',
              cues: ['4s inhale, 8s exhale', 'Longer exhale activates parasympathetic (rest and digest)', 'POTS: this helps regulate autonomic function post-session', 'Rise slowly when finished'],
              yt: 'breathing exercise parasympathetic POTS',
              bodyweight: true,
            },
          ],
        },
      ],
    },

    /* ── D7 · Full Rest ── */
    {
      id: 'D7',
      name: 'Full Rest',
      type: 'rest',
      duration: 0,
      note: 'Full rest day.',
      blocks: [],
    },

  ],
};
